import "./globals.css";
import Header from '@/components/header';
import Footer from "@/components/footer";

export const metadata = {
  title: "Química com pato =)",
  description: "Generated by create next app",
  charset: "utf-8",
  author: "Pat0v1sky",
  keywords: "Quimica"
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
